require:
    - "source-map-support/register"
recursive: true
full-trace: true
bail: true
reporter: "mocha-multi-reporters"
trace-warnings: true
spec:
    - "test/**/*.ts"
node-option:
    - "import=tsx"
    - "trace-warnings"
