# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

strategy:
  matrix:
    linux_node10:
      imageName: "ubuntu-latest"
      versionName: "10.x"
    linux_node12:
      imageName: "ubuntu-latest"
      versionName: "12.x"
    linux_node14:
      imageName: "ubuntu-latest"
      versionName: "14.x"
    linux_node16:
      imageName: "ubuntu-latest"
      versionName: "16.x"
    mac_node10:
      imageName: "macos-latest"
      versionName: "10.x"
    mac_node12:
      imageName: "macos-latest"
      versionName: "12.x"
    mac_node14:
      imageName: "macos-latest"
      versionName: "14.x"
    mac_node16:
      imageName: "macos-latest"
      versionName: "16.x"
    windows_node10:
      imageName: "windows-latest"
      versionName: "10.x"
    windows_node12:
      imageName: "windows-latest"
      versionName: "12.x"
    windows_node14:
      imageName: "windows-latest"
      versionName: "14.x"
    windows_node16:
      imageName: "windows-latest"
      versionName: "16.x"
  maxParallel: 10

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(versionName)
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm test
  displayName: 'npm install, build and test'
